### ISSUE TITLE
报错，为什么 

### ISSUE THREAD

**Issue by wgngoo** [Riete/aliyun-slb-exporter#1]
# _/usr/local/gopath/aliyun-slb-exporter
./main.go:21:23: cannot use slb (type exporter.SlbExporter) as type "github.com/prometheus/client_golang/prometheus".Collector in argument to registry.MustRegister:
	exporter.SlbExporter does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/riete/aliyun-slb-exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)

**Comment by Riete** [comment]
你这个可能是go mod的问题 用mod=vendor执行看下
